apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: ani-inference
  labels:
    app.kubernetes.io/part-of: ani-platform
    ani.kubercloud.io/workload-class: inference
    ani.kubercloud.io/platform-default: "true"
spec:
  weight: 10
  reclaimable: false
---
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  name: ani-training
  labels:
    app.kubernetes.io/part-of: ani-platform
    ani.kubercloud.io/workload-class: training
    ani.kubercloud.io/platform-default: "true"
spec:
  weight: 5
  reclaimable: true
