/**
 * ANI Core API client — types generated from Core OpenAPI Spec.
 *
 * Use for infrastructure APIs: instances, metering, tasks, registry, auth, etc.
 * Business APIs (models, knowledge-bases) use `@/api/client` instead.
 *
 * Usage:
 *   import { coreApi } from '@/api/coreClient'
 *   const { data } = await coreApi.GET('/metering/usage', { params: { query: { ... } } })
 *
 * GPU 规格与配额相关调用（SPEC §4.3）：
 *   - GET /gpu-specs/availability → 规格可用性四态标注（Console 创建 Dialog）
 *   - GET /gpu-scheduling/queues   → 调度队列列表（Console 创建 Dialog 队列下拉 + 设置页）
 *   - POST /instances (body.gpu.spec_id) → 按规格模式创建实例
 *   - GET /quotas/me        → 本租户配额（Console 列表页配额卡片）
 *   - GET /reservations/me  → 本租户预留额度视图（Console 列表页预留卡片）
 */
import createClient from 'openapi-fetch'
// core-schema.d.ts is generated by:
//   npx openapi-typescript api/openapi/v1.yaml -o frontends/console/src/api/core-schema.d.ts
// If this import fails, run: make gen-console-api
import type { paths } from './core-schema'

export const coreApi = createClient<paths>({
  baseUrl: '/api/v1',
  headers: {
    'Content-Type': 'application/json',
  },
})

export { setAuthToken } from './auth'
