/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsGpuPoolRouteImport } from './routes/ops/gpu-pool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsGpuPoolRoute = OpsGpuPoolRouteImport.update({
  id: '/ops/gpu-pool',
  path: '/ops/gpu-pool',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ops/gpu-pool': typeof OpsGpuPoolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ops/gpu-pool': typeof OpsGpuPoolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ops/gpu-pool': typeof OpsGpuPoolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ops/gpu-pool'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ops/gpu-pool'
  id: '__root__' | '/' | '/ops/gpu-pool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OpsGpuPoolRoute: typeof OpsGpuPoolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/gpu-pool': {
      id: '/ops/gpu-pool'
      path: '/ops/gpu-pool'
      fullPath: '/ops/gpu-pool'
      preLoaderRoute: typeof OpsGpuPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OpsGpuPoolRoute: OpsGpuPoolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
