/**
 * ANI Core API client for BOSS — types generated from Core OpenAPI Spec.
 *
 * BOSS consumes the same Core OpenAPI as Console, focusing on platform
 * admin scope endpoints (gpu-inventory, gpu-scheduling/queues, gpu-specs,
 * quotas, reservations). Tenant list for the quota drawer is derived from
 * GET /quotas (each Quota row carries a tenant_id).
 *
 * Usage:
 *   import { coreApi } from '@/api/coreClient'
 *   const { data } = await coreApi.GET('/gpu-inventory')
 *
 * Idempotency-Key helpers:
 *   import { newIdempotencyKey } from '@/api/coreClient'
 *   coreApi.PATCH('/gpu-inventory/{device_id}', {
 *     params: { header: { 'Idempotency-Key': newIdempotencyKey() }, path: { device_id } },
 *     body: { status: 'maintenance' },
 *   })
 */
import createClient from 'openapi-fetch'
// core-schema.d.ts is generated by:
//   node scripts/gen-core-schema.mjs
import type { paths } from './core-schema'

export const coreApi = createClient<paths>({
  baseUrl: '/api/v1',
  headers: {
    'Content-Type': 'application/json',
  },
})

/**
 * 生成 RFC4122 风格的幂等键。
 *
 * 对需要 Idempotency-Key 的写操作（POST/PUT/PATCH/DELETE GPU specs、
 * 配额、预留、设备状态）每次提交都应复用同一个 key 以支持重试去重；
 * 首次提交时调用此函数生成新 key。
 */
export function newIdempotencyKey(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID()
  }
  // Fallback (非安全上下文)
  return `idem-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`
}

export { setAuthToken } from './auth'
