/**
 * ANI Core API client for BOSS — types generated from Core OpenAPI Spec.
 *
 * BOSS consumes the same Core OpenAPI as Console, but only the platform
 * admin scope endpoints (gpu-inventory, gpu-scheduling/queues read-only).
 *
 * Usage:
 *   import { coreApi } from '@/api/coreClient'
 *   const { data } = await coreApi.GET('/gpu-inventory')
 */
import createClient from 'openapi-fetch'
// core-schema.d.ts is generated by:
//   node scripts/gen-core-schema.mjs
import type { paths } from './core-schema'

export const coreApi = createClient<paths>({
  baseUrl: '/api/v1',
  headers: {
    'Content-Type': 'application/json',
  },
})
