# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagEngineStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Parse = channel.unary_unary(
                '/rag.v1.RagEngine/Parse',
                request_serializer=rag__pb2.ParseRequest.SerializeToString,
                response_deserializer=rag__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/rag.v1.RagEngine/Embed',
                request_serializer=rag__pb2.EmbedRequest.SerializeToString,
                response_deserializer=rag__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.Generate = channel.unary_unary(
                '/rag.v1.RagEngine/Generate',
                request_serializer=rag__pb2.GenerateRequest.SerializeToString,
                response_deserializer=rag__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GenerateStream = channel.unary_stream(
                '/rag.v1.RagEngine/GenerateStream',
                request_serializer=rag__pb2.GenerateRequest.SerializeToString,
                response_deserializer=rag__pb2.GenerateToken.FromString,
                _registered_method=True)


class RagEngineServicer:
    """Missing associated documentation comment in .proto file."""

    def Parse(self, request, context):
        """Parse downloads a document from download_url, parses + chunks it, and
        returns the chunks (parents + children + images). Stateless.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Embed computes embedding vectors for the given texts. Stateless.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """Generate runs a single LLM completion over the question + context +
        history and returns the answer + token usage. Stateless.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStream(self, request, context):
        """GenerateStream is the streaming variant of Generate; yields tokens
        then a final done message with token usage. Stateless.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=rag__pb2.ParseRequest.FromString,
                    response_serializer=rag__pb2.ParseResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=rag__pb2.EmbedRequest.FromString,
                    response_serializer=rag__pb2.EmbedResponse.SerializeToString,
            ),
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=rag__pb2.GenerateRequest.FromString,
                    response_serializer=rag__pb2.GenerateResponse.SerializeToString,
            ),
            'GenerateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=rag__pb2.GenerateRequest.FromString,
                    response_serializer=rag__pb2.GenerateToken.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.v1.RagEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.v1.RagEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagEngine:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.RagEngine/Parse',
            rag__pb2.ParseRequest.SerializeToString,
            rag__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.RagEngine/Embed',
            rag__pb2.EmbedRequest.SerializeToString,
            rag__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.RagEngine/Generate',
            rag__pb2.GenerateRequest.SerializeToString,
            rag__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rag.v1.RagEngine/GenerateStream',
            rag__pb2.GenerateRequest.SerializeToString,
            rag__pb2.GenerateToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
